export default {
  STOP_LOADING: "STOP_LOADING",
  START_LOADING: "START_LOADING",
  START_SUCCESS: "START_SUCCESS",
  STOP_SUCCESS: "STOP_SUCCESS",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",

  //ZIPCODES
  FIND_ZIPCODES_BY_CENTER: "FIND_ZIPCODES_BY_CENTER"
};
